const AUTO_MARKET_ROUTE_FALLBACK_CODES = new Set([
  'NETWORK_ERROR',
  'PROVIDER_RATE_LIMITED',
  'PROVIDER_TIMEOUT',
  'PROVIDER_UNAVAILABLE',
  'PROVIDER_REJECTED',
  'RAYDIUM_BUILD_FAILED',
  'ORCA_POOL_UNAVAILABLE',
  'JUPITER_BUILD_FAILED',
  'JUPITER_GASLESS_MINIMUM',
  'NO_DIRECT_ROUTE',
  'BLOCKHASH_EXPIRED',
  'SLIPPAGE_EXCEEDED',
]);

export function isAutoMarketRouteFallbackCode(code: string): boolean {
  return AUTO_MARKET_ROUTE_FALLBACK_CODES.has(code);
}
